project_id = "tjikwxkmsfmyjkssvyoh"

[functions.changenow]
verify_jwt = false

[functions.auto-publish-blog]
verify_jwt = false

[functions.dynamic-feed]
verify_jwt = false

[functions.ping-search-engines]
verify_jwt = false

[functions.coingecko-prices]
verify_jwt = false

[functions.x-sales-agent]
verify_jwt = false

[functions.live-rates]
verify_jwt = false

[functions.rates-xml]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.send-transactional-email]
verify_jwt = true

[functions.preview-transactional-email]
verify_jwt = false

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false