project_id = "tjikwxkmsfmyjkssvyoh"

[functions.changenow]
verify_jwt = false

[functions.auto-publish-blog]
verify_jwt = false

[functions.dynamic-feed]
verify_jwt = false

[functions.ping-search-engines]
verify_jwt = false