project_id = "tjikwxkmsfmyjkssvyoh"

[functions.coinrabbit]
verify_jwt = false

[functions.changenow]
verify_jwt = false

[functions.auto-publish-blog]
verify_jwt = false

[functions.dynamic-feed]
verify_jwt = false

[functions.ping-search-engines]
verify_jwt = false

[functions.coingecko-prices]
verify_jwt = false

[functions.x-sales-agent]
verify_jwt = false

[functions.live-rates]
verify_jwt = false

[functions.rates-xml]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.send-transactional-email]
verify_jwt = true

[functions.preview-transactional-email]
verify_jwt = false

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.guardarian]
verify_jwt = false

[functions.smtp-send]
verify_jwt = false

[functions.partner-update-token]
verify_jwt = false

[functions.telegram-notify]
verify_jwt = false

[functions.webhook-dispatcher]
verify_jwt = false

[functions.partner-proxy]
verify_jwt = false

[functions.sync-assets]
verify_jwt = false

[functions.dynamic-sitemap]
verify_jwt = false