/**
 * Vite plugin: generate-sitemaps
 *
 * Runs during `vite build` (closeBundle hook, after dist is fully written).
 * Fetches every pair URL from the dynamic-feed edge function, splits into
 * 5,000-URL chunks (~9 MB each, well under the 50 MB / 50,000-URL sitemap.org
 * limit), writes them as real .xml files into dist/, and rewrites
 * dist/sitemap.xml as a same-host sitemap index.
 *
 * Why dist/ and not public/?
 *   - Pair sitemaps total ~500 MB of XML; committing them would bloat the repo.
 *   - dist/ is regenerated every build, then deployed by Lovable hosting,
 *     which serves the apex domain reliably for real files (unlike _redirects
 *     proxy rules for /sitemap-* paths, which are NOT honored).
 *
 * Result: every publish ships a 100% fresh sitemap covering every pair in the
 * database, automatically split across as many sitemap-pairs-N.xml files as
 * needed. New pairs added by the sync engine appear at the next deploy.
 */
import type { Plugin } from "vite";
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const SUPABASE_URL = "https://tjikwxkmsfmyjkssvyoh.supabase.co";
const FEED_BASE = `${SUPABASE_URL}/functions/v1/dynamic-feed?p=`;
// 1,000 URLs/file keeps each sitemap ~1.6 MB. Larger files (we previously
// shipped 5,000/file = ~8.2 MB) are technically valid per sitemaps.org but
// Googlebot frequently times out fetching them, which surfaces in Search
// Console as "Couldn't fetch" on a random subset of children every crawl.
const URLS_PER_FILE = 1000;
const URL_RE = /<url>[\s\S]*?<\/url>/g;

async function fetchSourceBatch(idx: number): Promise<string | null> {
  try {
    const res = await fetch(`${FEED_BASE}/sitemap-pairs-${idx}.xml`);
    if (!res.ok) return null;
    return await res.text();
  } catch {
    return null;
  }
}

function wrapUrlset(entries: string[]): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${entries.join("\n")}
</urlset>
`;
}

function wrapIndex(childPaths: string[]): string {
  const today = new Date().toISOString().slice(0, 10);
  const items = childPaths
    .map(
      (p) =>
        `  <sitemap><loc>https://mrcglobalpay.com/${p}</loc><lastmod>${today}</lastmod></sitemap>`,
    )
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Sitemap index for mrcglobalpay.com — auto-generated by the
  generate-sitemaps Vite plugin on every build.
  Children are real static files in dist/ so they resolve on the apex domain.
  New pairs from the sync engine appear in the next deploy automatically.
-->
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${items}
</sitemapindex>
`;
}

function writeXmlAndAlias(outDir: string, filename: string, content: string) {
  writeFileSync(join(outDir, filename), content, "utf8");
  if (filename.endsWith(".xml")) {
    writeFileSync(join(outDir, filename.slice(0, -4)), content, "utf8");
  }
}

export function generateSitemaps(outDir = "dist"): Plugin {
  return {
    name: "generate-sitemaps",
    apply: "build",
    async closeBundle() {
      const log = (msg: string) => console.log(`[sitemaps] ${msg}`);
      log("Starting sitemap generation…");

      try {
        mkdirSync(outDir, { recursive: true });

        // --- 1. Fetch all pair URLs ---------------------------------------
        const allUrls: string[] = [];
        let sourceIdx = 0;
        let consecutiveEmpty = 0;
        while (consecutiveEmpty < 2 && sourceIdx < 100) {
          const xml = await fetchSourceBatch(sourceIdx);
          if (!xml) {
            consecutiveEmpty++;
          } else {
            const entries = xml.match(URL_RE) ?? [];
            if (entries.length === 0) {
              consecutiveEmpty++;
            } else {
              consecutiveEmpty = 0;
              allUrls.push(...entries);
              log(
                `  source batch ${sourceIdx}: +${entries.length.toLocaleString()} URLs (running total: ${allUrls.length.toLocaleString()})`,
              );
            }
          }
          sourceIdx++;
        }

        if (allUrls.length === 0) {
          log("⚠ No pair URLs returned — keeping default sitemap.xml from public/.");
          return;
        }

        log(`Total pair URLs: ${allUrls.length.toLocaleString()}`);

        // --- 2. Write static + blog + assets sitemaps ---------------------
        // sitemap-assets.xml ships per-token hub URLs (/asset/:ticker × 13 langs)
        // with bidirectional hreflang. Source = dynamic-sitemap/assets.xml on
        // the edge function (different host than dynamic-feed).
        const childPaths: string[] = [];

        // Pull assets sitemap from dynamic-sitemap (separate function).
        try {
          const assetsRes = await fetch(
            `${SUPABASE_URL}/functions/v1/dynamic-sitemap/assets.xml`,
          );
          if (assetsRes.ok) {
            writeXmlAndAlias(outDir, "sitemap-assets.xml", await assetsRes.text());
            childPaths.push("sitemap-assets.xml");
            log("  wrote sitemap-assets.xml");
          }
        } catch (e) {
          log(`  ⚠ failed to fetch sitemap-assets.xml: ${(e as Error).message}`);
        }

        for (const name of ["sitemap-static.xml", "sitemap-blog.xml"]) {
          try {
            const res = await fetch(`${FEED_BASE}/${name}`);
            if (res.ok) {
              writeXmlAndAlias(outDir, name, await res.text());
              childPaths.push(name);
              log(`  wrote ${name}`);
            }
          } catch (e) {
            log(`  ⚠ failed to fetch ${name}: ${(e as Error).message}`);
          }
        }

        // --- 3. Split into 5,000-URL pair files ---------------------------
        const totalFiles = Math.ceil(allUrls.length / URLS_PER_FILE);
        for (let i = 0; i < totalFiles; i++) {
          const slice = allUrls.slice(i * URLS_PER_FILE, (i + 1) * URLS_PER_FILE);
          const filename = `sitemap-pairs-${i}.xml`;
          writeFileSync(join(outDir, filename), wrapUrlset(slice), "utf8");
          childPaths.push(filename);
        }
        log(
          `Wrote ${totalFiles} pair sitemap files (${URLS_PER_FILE.toLocaleString()} URLs each).`,
        );

        // --- 4. Rewrite the same-host sitemap index -----------------------
        writeFileSync(join(outDir, "sitemap.xml"), wrapIndex(childPaths), "utf8");
        log(
          `✓ Wrote sitemap.xml index with ${childPaths.length} children (covers ${allUrls.length.toLocaleString()} URLs).`,
        );
      } catch (err) {
        // Never fail the build because of sitemap generation issues.
        log(`✗ Generation failed (build continues): ${(err as Error).message}`);
      }
    },
  };
}
