import { useTranslation } from "react-i18next";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import {
  Shield,
  Wallet,
  Clock,
  Settings,
  RotateCcw,
  Coins,
  Send,
  CalendarClock,
  Unlock,
  Lock,
  Bell,
  Building2,
  ShieldCheck,
  HelpCircle,
  AlertTriangle,
  TrendingDown,
  Zap,
  Infinity,
  DollarSign,
  CheckCircle2,
} from "lucide-react";

/* ────────────────────────────────────────────────────────────── */
/*  Loan Steps – CoinRabbit-verified logic                       */
/* ────────────────────────────────────────────────────────────── */
const LOAN_STEPS = [
  {
    icon: Settings,
    titleKey: "lendGuide.loan.step1Title",
    descKey: "lendGuide.loan.step1Desc",
    fallbackTitle: "Collateral & LTV Selection",
    fallbackDesc:
      "Choose your collateral asset (BTC, ETH, BNB, and 130+ others) and set your Loan-to-Value ratio. Available tiers are 50%, 70%, 80%, and 90%. A higher LTV unlocks more stablecoins upfront but leaves a thinner safety buffer against market drops. A lower LTV (50%) provides maximum protection and the lowest interest rate.",
  },
  {
    icon: Send,
    titleKey: "lendGuide.loan.step2Title",
    descKey: "lendGuide.loan.step2Desc",
    fallbackTitle: "Transfer Collateral",
    fallbackDesc:
      "Send collateral to the unique deposit address generated by the system. Our infrastructure monitors the blockchain and requires 2 network confirmations before proceeding. The address is single-use and secured by multisig cold-storage wallets.",
  },
  {
    icon: Wallet,
    titleKey: "lendGuide.loan.step3Title",
    descKey: "lendGuide.loan.step3Desc",
    fallbackTitle: "Receive Stablecoin Payout",
    fallbackDesc:
      "Once confirmations are received, stablecoins (USDT or USDC) are dispatched to your provided payout address. Delivery typically completes within 10 minutes of blockchain confirmation.",
  },
  {
    icon: CalendarClock,
    titleKey: "lendGuide.loan.step4Title",
    descKey: "lendGuide.loan.step4Desc",
    fallbackTitle: "Loan Management & Repayment",
    fallbackDesc:
      "No monthly interest payments are required. Interest is calculated based on the Annual Percentage Rate (APR) for your selected asset and LTV tier, and is simply added to the total repayment amount. Repay the principal plus accrued interest at any time — there are no early repayment penalties — to instantly unlock and receive your collateral back.",
  },
];

/* ────────────────────────────────────────────────────────────── */
/*  Earn Steps                                                   */
/* ────────────────────────────────────────────────────────────── */
const EARN_STEPS = [
  {
    icon: Coins,
    titleKey: "lendGuide.earn.step1Title",
    descKey: "lendGuide.earn.step1Desc",
    fallbackTitle: "Choose Your Asset",
    fallbackDesc:
      "Select from stablecoins (USDT, USDC) or major assets (BTC, ETH) and more. Each asset offers a competitive Annual Percentage Yield (APY) displayed in real-time.",
  },
  {
    icon: Send,
    titleKey: "lendGuide.earn.step2Title",
    descKey: "lendGuide.earn.step2Desc",
    fallbackTitle: "Deposit",
    fallbackDesc:
      "Send your chosen asset to the unique deposit address provided. You can start earning with as little as $100 equivalent.",
  },
  {
    icon: Clock,
    titleKey: "lendGuide.earn.step3Title",
    descKey: "lendGuide.earn.step3Desc",
    fallbackTitle: "Daily Accrual & Compounding",
    fallbackDesc:
      "Interest is accrued every day and automatically compounded into your balance. Your earnings generate additional yield over time without any action required from you.",
  },
  {
    icon: Unlock,
    titleKey: "lendGuide.earn.step4Title",
    descKey: "lendGuide.earn.step4Desc",
    fallbackTitle: "Complete Flexibility",
    fallbackDesc:
      "There are no lock-up periods and no withdrawal fees. Withdraw your full principal and all earned interest 24/7, whenever you choose.",
  },
];

/* ────────────────────────────────────────────────────────────── */
/*  Safety items                                                 */
/* ────────────────────────────────────────────────────────────── */
const SAFETY_ITEMS = [
  {
    icon: Lock,
    titleKey: "lendGuide.safety.coldTitle",
    descKey: "lendGuide.safety.coldDesc",
    fallbackTitle: "Cold Storage Custody",
    fallbackDesc:
      "All collateral and deposits are secured in multisig cold-storage wallets, air-gapped from online systems.",
  },
  {
    icon: Shield,
    titleKey: "lendGuide.safety.rehypTitle",
    descKey: "lendGuide.safety.rehypDesc",
    fallbackTitle: "Strict No-Rehypothecation",
    fallbackDesc:
      "Your assets are never lent out, traded, or used as collateral for other positions. What you deposit is exactly what you get back.",
  },
  {
    icon: Bell,
    titleKey: "lendGuide.safety.realtimeTitle",
    descKey: "lendGuide.safety.realtimeDesc",
    fallbackTitle: "Real-Time Risk Alerts",
    fallbackDesc:
      "Receive instant SMS and email notifications if collateral value approaches the risk zone, giving you time to top up and prevent liquidation.",
  },
  {
    icon: Building2,
    titleKey: "lendGuide.safety.msbTitle",
    descKey: "lendGuide.safety.msbDesc",
    fallbackTitle: "Canadian MSB Status",
    fallbackDesc:
      "Services in Canada are provided by a registered Money Services Business (MSB C100000015), operating under FINTRAC oversight and federal AML/ATF guidelines.",
  },
];

/* ────────────────────────────────────────────────────────────── */
/*  Loan FAQ – 6 questions                                       */
/* ────────────────────────────────────────────────────────────── */
const LOAN_FAQ = [
  {
    qKey: "lendGuide.loanFaq.q1",
    aKey: "lendGuide.loanFaq.a1",
    fallbackQ: "What happens if the price of my collateral drops?",
    fallbackA:
      "MRC GlobalPay actively monitors all open loan positions. If your collateral value enters the Yellow (Risk) zone, you will receive instant SMS and email alerts with instructions to top up. If the value declines further into the Red (Liquidation) zone without action, the system will automatically sell enough collateral to repay the loan — protecting you from further losses.",
  },
  {
    qKey: "lendGuide.loanFaq.q2",
    aKey: "lendGuide.loanFaq.a2",
    fallbackQ: "Are there any hidden fees?",
    fallbackA:
      "No. The only cost is the transparent interest rate (APR) displayed before you confirm the loan. There are no origination fees, no monthly service charges, and no early repayment penalties.",
  },
  {
    qKey: "lendGuide.loanFaq.q3",
    aKey: "lendGuide.loanFaq.a3",
    fallbackQ: "How is interest calculated?",
    fallbackA:
      "Interest is based on the Annual Percentage Rate (APR) specific to your collateral asset and chosen LTV tier. It accrues daily and is added to the total repayment amount. There are no monthly payment schedules — you repay the full amount (principal + accrued interest) whenever you are ready.",
  },
  {
    qKey: "lendGuide.loanFaq.q4",
    aKey: "lendGuide.loanFaq.a4",
    fallbackQ: "Can I repay my loan early?",
    fallbackA:
      "Yes. There are absolutely no early repayment penalties. Repay the principal plus accrued interest at any time, and your collateral is unlocked and returned to you instantly.",
  },
  {
    qKey: "lendGuide.loanFaq.q5",
    aKey: "lendGuide.loanFaq.a5",
    fallbackQ: "What LTV ratio should I choose?",
    fallbackA:
      "It depends on your risk tolerance. A 50% LTV gives you the largest safety buffer against price drops and the lowest interest rate, but fewer upfront funds. A 90% LTV maximizes your borrowing power but has a tighter liquidation margin. For most users, 70% offers a balanced middle ground.",
  },
  {
    qKey: "lendGuide.loanFaq.q6",
    aKey: "lendGuide.loanFaq.a6",
    fallbackQ: "Is there a minimum or maximum loan amount?",
    fallbackA:
      "The minimum depends on the collateral asset and is displayed in the calculator. There is no hard maximum — larger positions may undergo additional compliance review in accordance with Canadian MSB regulations.",
  },
];

/* ────────────────────────────────────────────────────────────── */
/*  Earn FAQ – 5 questions                                       */
/* ────────────────────────────────────────────────────────────── */
const EARN_FAQ = [
  {
    qKey: "lendGuide.earnFaq.q1",
    aKey: "lendGuide.earnFaq.a1",
    fallbackQ: "Is there a lock-up period?",
    fallbackA:
      "No. MRC GlobalPay Earn is completely flexible. You can withdraw your full principal and all earned interest at any time, 24/7, with no penalties and no withdrawal fees.",
  },
  {
    qKey: "lendGuide.earnFaq.q2",
    aKey: "lendGuide.earnFaq.a2",
    fallbackQ: "How often is interest paid?",
    fallbackA:
      "Interest is accrued daily and automatically compounded into your balance. Your earnings generate additional yield over time without any manual action.",
  },
  {
    qKey: "lendGuide.earnFaq.q3",
    aKey: "lendGuide.earnFaq.a3",
    fallbackQ: "What is the minimum deposit?",
    fallbackA:
      "You can start earning with as little as $100 equivalent, depending on the selected asset.",
  },
  {
    qKey: "lendGuide.earnFaq.q4",
    aKey: "lendGuide.earnFaq.a4",
    fallbackQ: "Are my funds safe?",
    fallbackA:
      "All funds are secured in multisig cold-storage wallets with a strict no-rehypothecation policy — your assets are never lent out or traded. The platform operates under the oversight of a registered Canadian MSB (C100000015).",
  },
  {
    qKey: "lendGuide.earnFaq.q5",
    aKey: "lendGuide.earnFaq.a5",
    fallbackQ: "Are there any hidden fees or charges?",
    fallbackA:
      "No. There are no deposit fees, no withdrawal fees, and no management charges. The APY displayed is the net rate you earn.",
  },
];

/* ────────────────────────────────────────────────────────────── */
/*  Earn Flexibility Highlights                                  */
/* ────────────────────────────────────────────────────────────── */
const EARN_HIGHLIGHTS = [
  {
    icon: Infinity,
    titleKey: "lendGuide.earnHighlight.unlimitedTitle",
    descKey: "lendGuide.earnHighlight.unlimitedDesc",
    fallbackTitle: "Unlimited Term",
    fallbackDesc: "No expiry date. Your savings grow for as long as you choose.",
  },
  {
    icon: Zap,
    titleKey: "lendGuide.earnHighlight.instantTitle",
    descKey: "lendGuide.earnHighlight.instantDesc",
    fallbackTitle: "Instant Withdrawals",
    fallbackDesc: "Principal and interest can be withdrawn 24/7 with zero lock-up periods.",
  },
  {
    icon: DollarSign,
    titleKey: "lendGuide.earnHighlight.minimumTitle",
    descKey: "lendGuide.earnHighlight.minimumDesc",
    fallbackTitle: "Low Minimums",
    fallbackDesc: "Start earning yield with as little as $100 equivalent.",
  },
];

/* ────────────────────────────────────────────────────────────── */
/*  Reusable Step Row (vertical timeline)                        */
/* ────────────────────────────────────────────────────────────── */
function StepRow({
  step,
  index,
  total,
}: {
  step: (typeof LOAN_STEPS)[0];
  index: number;
  total: number;
}) {
  const { t } = useTranslation();
  const Icon = step.icon;
  return (
    <div className="flex items-start gap-4 sm:gap-5">
      <div className="flex flex-col items-center">
        <div className="relative flex h-12 w-12 items-center justify-center rounded-full border-2 border-[#D4AF37]/40 bg-[#D4AF37]/10">
          <span className="absolute -top-2 -end-2 flex h-6 w-6 items-center justify-center rounded-full bg-[#D4AF37] text-[11px] font-bold text-background">
            {index + 1}
          </span>
          <Icon className="h-5 w-5 text-[#D4AF37]" />
        </div>
        {index < total - 1 && (
          <div className="h-full min-h-[2.5rem] w-px bg-gradient-to-b from-[#D4AF37]/40 via-[#D4AF37]/20 to-transparent" />
        )}
      </div>
      <div className="pt-1.5 pb-6">
        <h3 className="font-semibold text-foreground text-base">
          {t(step.titleKey, step.fallbackTitle)}
        </h3>
        <p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">
          {t(step.descKey, step.fallbackDesc)}
        </p>
      </div>
    </div>
  );
}

/* ────────────────────────────────────────────────────────────── */
/*  FAQ Accordion                                                */
/* ────────────────────────────────────────────────────────────── */
function FaqBlock({ items }: { items: typeof LOAN_FAQ }) {
  const { t } = useTranslation();
  return (
    <div className="space-y-4">
      <h3 className="flex items-center gap-2 text-lg font-semibold text-foreground">
        <HelpCircle className="h-5 w-5 text-[#D4AF37]" />
        {t("lendGuide.faqTitle", "Frequently Asked Questions")}
      </h3>
      <Accordion type="single" collapsible className="w-full">
        {items.map((item, i) => (
          <AccordionItem key={i} value={`faq-${i}`} className="border-border/40">
            <AccordionTrigger className="text-sm font-medium text-foreground hover:text-[#D4AF37] hover:no-underline text-start">
              {t(item.qKey, item.fallbackQ)}
            </AccordionTrigger>
            <AccordionContent className="text-sm leading-relaxed text-muted-foreground">
              {t(item.aKey, item.fallbackA)}
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  );
}

/* ────────────────────────────────────────────────────────────── */
/*  Pro-Tip Risk Zone Warning                                    */
/* ────────────────────────────────────────────────────────────── */
function RiskZoneWarning() {
  const { t } = useTranslation();
  return (
    <div className="rounded-xl border border-[#D4AF37]/30 bg-[#D4AF37]/5 p-5">
      <div className="flex items-start gap-3">
        <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-[#D4AF37]/15">
          <AlertTriangle className="h-4.5 w-4.5 text-[#D4AF37]" />
        </div>
        <div>
          <h4 className="font-semibold text-foreground text-sm flex items-center gap-1.5">
            <span className="text-[#D4AF37]">Pro Tip</span> — Risk Zone Alerts
          </h4>
          <p className="mt-1 text-xs leading-relaxed text-muted-foreground">
            {t(
              "lendGuide.riskZoneTip",
              "MRC GlobalPay actively monitors all open loan positions. If your collateral value enters the Yellow (Risk) zone, you will receive instant SMS and email alerts with instructions to top up. If the value declines further into the Red (Liquidation) zone without action, the system will automatically sell enough collateral to repay the loan — protecting you from further losses."
            )}
          </p>
        </div>
      </div>
    </div>
  );
}

/* ────────────────────────────────────────────────────────────── */
/*  Why Your Assets Are Safe – Security Deep-Dive                */
/* ────────────────────────────────────────────────────────────── */
function SecurityDeepDive() {
  const { t } = useTranslation();
  return (
    <Card className="border-[#D4AF37]/20 bg-card/40 backdrop-blur-sm overflow-hidden">
      <div className="relative">
        <div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-transparent via-[#D4AF37] to-transparent" />
        <div className="p-6 sm:p-8 space-y-6">
          <div className="flex items-center gap-3">
            <div className="flex h-11 w-11 items-center justify-center rounded-full border-2 border-[#D4AF37]/40 bg-[#D4AF37]/10">
              <ShieldCheck className="h-5 w-5 text-[#D4AF37]" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-foreground">
                {t("lendGuide.safetyTitle", "Why Your Assets Are Safe")}
              </h2>
              <p className="text-xs text-muted-foreground">
                {t("lendGuide.safetySubtitle", "Institutional-grade security backed by Canadian MSB compliance")}
              </p>
            </div>
          </div>

          <div className="grid gap-4 sm:grid-cols-2">
            {SAFETY_ITEMS.map((item) => {
              const Icon = item.icon;
              return (
                <div
                  key={item.titleKey}
                  className="group rounded-xl border border-border/40 bg-background/40 p-5 transition-colors hover:border-[#D4AF37]/30"
                >
                  <div className="mb-3 flex h-10 w-10 items-center justify-center rounded-lg bg-[#D4AF37]/10">
                    <Icon className="h-5 w-5 text-[#D4AF37]" />
                  </div>
                  <h3 className="font-semibold text-foreground text-sm">
                    {t(item.titleKey, item.fallbackTitle)}
                  </h3>
                  <p className="mt-1.5 text-xs leading-relaxed text-muted-foreground">
                    {t(item.descKey, item.fallbackDesc)}
                  </p>
                </div>
              );
            })}
          </div>

          <div className="flex flex-wrap items-center justify-center gap-2 pt-2">
            <Badge variant="outline" className="border-[#D4AF37]/40 text-[#D4AF37] text-[10px]">
              MSB C100000015
            </Badge>
            <Badge variant="outline" className="border-border/40 text-muted-foreground text-[10px]">
              FINTRAC Regulated
            </Badge>
            <Badge variant="outline" className="border-border/40 text-muted-foreground text-[10px]">
              No Rehypothecation
            </Badge>
            <Badge variant="outline" className="border-border/40 text-muted-foreground text-[10px]">
              Cold Storage
            </Badge>
          </div>
        </div>
      </div>
    </Card>
  );
}

/* ────────────────────────────────────────────────────────────── */
/*  Earn Flexibility Highlights Section                          */
/* ────────────────────────────────────────────────────────────── */
function EarnFlexibilitySection() {
  const { t } = useTranslation();
  return (
    <div className="space-y-4">
      <h3 className="text-lg font-semibold text-foreground">
        {t("lendGuide.earnFlexTitle", "Flexibility Highlights")}
      </h3>
      <div className="grid gap-3 sm:grid-cols-3">
        {EARN_HIGHLIGHTS.map((item) => {
          const Icon = item.icon;
          return (
            <div
              key={item.titleKey}
              className="flex items-start gap-3 rounded-xl border border-border/40 bg-background/40 p-4"
            >
              <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-[#D4AF37]/10">
                <Icon className="h-4 w-4 text-[#D4AF37]" />
              </div>
              <div>
                <h4 className="font-semibold text-foreground text-sm">
                  {t(item.titleKey, item.fallbackTitle)}
                </h4>
                <p className="mt-0.5 text-xs leading-relaxed text-muted-foreground">
                  {t(item.descKey, item.fallbackDesc)}
                </p>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

/* ────────────────────────────────────────────────────────────── */
/*  Exported: Loan Product Guide                                 */
/* ────────────────────────────────────────────────────────────── */
export function LoanProductGuide() {
  const { t } = useTranslation();
  return (
    <section className="space-y-8">
      {/* Step-by-step timeline */}
      <Card className="border-border/40 bg-card/40 backdrop-blur-sm">
        <CardContent className="p-6 sm:p-8 space-y-8">
          <div className="space-y-2">
            <h2 className="text-xl font-bold text-foreground">
              {t("lendGuide.loanTitle", "How Crypto Loans Work")}
            </h2>
            <p className="text-sm text-muted-foreground max-w-2xl">
              {t(
                "lendGuide.loanSubtitle",
                "From collateral selection to stablecoin payout — a step-by-step guide to borrowing against your crypto without selling it."
              )}
            </p>
          </div>

          <div>
            {LOAN_STEPS.map((step, i) => (
              <StepRow key={step.titleKey} step={step} index={i} total={LOAN_STEPS.length} />
            ))}
          </div>

          {/* Pro-Tip risk zone warning */}
          <RiskZoneWarning />

          {/* FAQ */}
          <FaqBlock items={LOAN_FAQ} />
        </CardContent>
      </Card>

      {/* Security deep-dive */}
      <SecurityDeepDive />
    </section>
  );
}

/* ────────────────────────────────────────────────────────────── */
/*  Exported: Earn Product Guide                                 */
/* ────────────────────────────────────────────────────────────── */
export function EarnProductGuide() {
  const { t } = useTranslation();
  return (
    <section className="space-y-8">
      {/* Step-by-step timeline */}
      <Card className="border-border/40 bg-card/40 backdrop-blur-sm">
        <CardContent className="p-6 sm:p-8 space-y-8">
          <div className="space-y-2">
            <h2 className="text-xl font-bold text-foreground">
              {t("lendGuide.earnTitle", "How Earn Interest Works")}
            </h2>
            <p className="text-sm text-muted-foreground max-w-2xl">
              {t(
                "lendGuide.earnSubtitle",
                "Deposit your crypto, earn daily compounding interest, and withdraw anytime — no lock-ups, no fees."
              )}
            </p>
          </div>

          <div>
            {EARN_STEPS.map((step, i) => (
              <StepRow key={step.titleKey} step={step} index={i} total={EARN_STEPS.length} />
            ))}
          </div>

          {/* Flexibility highlights */}
          <EarnFlexibilitySection />

          {/* FAQ */}
          <FaqBlock items={EARN_FAQ} />
        </CardContent>
      </Card>

      {/* Security deep-dive */}
      <SecurityDeepDive />
    </section>
  );
}
