import { useTranslation } from "react-i18next";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import {
  Shield,
  Wallet,
  Clock,
  ArrowRight,
  Settings,
  RotateCcw,
  Coins,
  Send,
  CalendarClock,
  Unlock,
  Lock,
  Bell,
  Building2,
  ShieldCheck,
  HelpCircle,
} from "lucide-react";

/* ────────────────────────────────────────────────────────────── */
/*  Data                                                         */
/* ────────────────────────────────────────────────────────────── */

const LOAN_STEPS = [
  {
    icon: Settings,
    titleKey: "lendGuide.loan.step1Title",
    descKey: "lendGuide.loan.step1Desc",
    fallbackTitle: "Set Your Terms",
    fallbackDesc:
      "Use the calculator to select your collateral asset (BTC, ETH, etc.) and a Loan-to-Value ratio between 50% and 90%.",
  },
  {
    icon: Send,
    titleKey: "lendGuide.loan.step2Title",
    descKey: "lendGuide.loan.step2Desc",
    fallbackTitle: "Transfer Collateral",
    fallbackDesc:
      "Send the required crypto amount to the secure deposit address generated by the system.",
  },
  {
    icon: Wallet,
    titleKey: "lendGuide.loan.step3Title",
    descKey: "lendGuide.loan.step3Desc",
    fallbackTitle: "Receive Funds",
    fallbackDesc:
      "Stablecoins (USDT/USDC) are typically delivered to your payout address within 10 minutes of blockchain confirmation.",
  },
  {
    icon: CalendarClock,
    titleKey: "lendGuide.loan.step4Title",
    descKey: "lendGuide.loan.step4Desc",
    fallbackTitle: "Managing the Loan",
    fallbackDesc:
      "There are no monthly payments and no fixed repayment deadlines. Interest is calculated based on the APR and added to the total repayment amount.",
  },
  {
    icon: RotateCcw,
    titleKey: "lendGuide.loan.step5Title",
    descKey: "lendGuide.loan.step5Desc",
    fallbackTitle: "Repayment",
    fallbackDesc:
      "Repay the principal plus accrued interest at any time to instantly unlock and receive your collateral back.",
  },
];

const EARN_STEPS = [
  {
    icon: Coins,
    titleKey: "lendGuide.earn.step1Title",
    descKey: "lendGuide.earn.step1Desc",
    fallbackTitle: "Choose Your Asset",
    fallbackDesc:
      "Select from stablecoins (USDT/USDC) or major coins (BTC/ETH) to start earning yield.",
  },
  {
    icon: Send,
    titleKey: "lendGuide.earn.step2Title",
    descKey: "lendGuide.earn.step2Desc",
    fallbackTitle: "Deposit",
    fallbackDesc:
      "Send the asset to the unique deposit address provided. The minimum deposit starts from $100 equivalent.",
  },
  {
    icon: Clock,
    titleKey: "lendGuide.earn.step3Title",
    descKey: "lendGuide.earn.step3Desc",
    fallbackTitle: "Daily Accrual",
    fallbackDesc:
      "Interest is accrued daily and automatically compounded into your balance.",
  },
  {
    icon: Unlock,
    titleKey: "lendGuide.earn.step4Title",
    descKey: "lendGuide.earn.step4Desc",
    fallbackTitle: "Complete Flexibility",
    fallbackDesc:
      "There are no lock-up periods. Withdraw your full principal and all earned interest whenever you choose — no withdrawal fees.",
  },
];

const SAFETY_ITEMS = [
  {
    icon: Lock,
    titleKey: "lendGuide.safety.coldTitle",
    descKey: "lendGuide.safety.coldDesc",
    fallbackTitle: "Cold Storage Custody",
    fallbackDesc:
      "Collateral is held in multisig cold wallets and is never reused (No Rehypothecation).",
  },
  {
    icon: Bell,
    titleKey: "lendGuide.safety.realtimeTitle",
    descKey: "lendGuide.safety.realtimeDesc",
    fallbackTitle: "Real-Time Protection",
    fallbackDesc:
      "Receive SMS and email notifications if collateral value drops, allowing for manual top-ups to prevent liquidation.",
  },
  {
    icon: Building2,
    titleKey: "lendGuide.safety.msbTitle",
    descKey: "lendGuide.safety.msbDesc",
    fallbackTitle: "Canadian MSB Status",
    fallbackDesc:
      "Services in Canada are provided by a registered Money Services Business (MSB), ensuring compliance with local financial standards.",
  },
];

const LOAN_FAQ = [
  {
    qKey: "lendGuide.loanFaq.q1",
    aKey: "lendGuide.loanFaq.a1",
    fallbackQ: "What happens if my collateral value drops?",
    fallbackA:
      "You will receive notifications (SMS and email) when your collateral approaches the liquidation threshold. You can top up additional collateral at any time to maintain a healthy Loan-to-Value ratio and avoid liquidation.",
  },
  {
    qKey: "lendGuide.loanFaq.q2",
    aKey: "lendGuide.loanFaq.a2",
    fallbackQ: "Is there a minimum or maximum loan amount?",
    fallbackA:
      "The minimum loan amount depends on the collateral asset and is shown in the calculator. There is no hard maximum — larger amounts may require additional compliance review.",
  },
  {
    qKey: "lendGuide.loanFaq.q3",
    aKey: "lendGuide.loanFaq.a3",
    fallbackQ: "How is interest calculated?",
    fallbackA:
      "Interest is calculated based on the Annual Percentage Rate (APR) for your selected asset and LTV. It accrues daily and is added to the total repayment amount, but there are no monthly payment schedules.",
  },
  {
    qKey: "lendGuide.loanFaq.q4",
    aKey: "lendGuide.loanFaq.a4",
    fallbackQ: "Can I repay my loan early?",
    fallbackA:
      "Yes. There are no early repayment penalties. You can repay the principal plus accrued interest at any time to unlock your collateral instantly.",
  },
];

const EARN_FAQ = [
  {
    qKey: "lendGuide.earnFaq.q1",
    aKey: "lendGuide.earnFaq.a1",
    fallbackQ: "Is there a lock-up period?",
    fallbackA:
      "No. MRC GlobalPay Earn is completely flexible. You can withdraw your full principal and all earned interest at any time with no penalties and no withdrawal fees.",
  },
  {
    qKey: "lendGuide.earnFaq.q2",
    aKey: "lendGuide.earnFaq.a2",
    fallbackQ: "How often is interest paid?",
    fallbackA:
      "Interest is accrued daily and automatically compounded into your balance. You can view your real-time balance at any time.",
  },
  {
    qKey: "lendGuide.earnFaq.q3",
    aKey: "lendGuide.earnFaq.a3",
    fallbackQ: "What is the minimum deposit?",
    fallbackA:
      "The minimum deposit starts from the equivalent of $100 USD, depending on the selected asset.",
  },
  {
    qKey: "lendGuide.earnFaq.q4",
    aKey: "lendGuide.earnFaq.a4",
    fallbackQ: "Are my funds safe?",
    fallbackA:
      "Funds are held in multisig cold-storage wallets and are never rehypothecated. Our platform operates under the oversight of a registered Canadian MSB (C100000015).",
  },
];

/* ────────────────────────────────────────────────────────────── */
/*  Reusable Step Row                                            */
/* ────────────────────────────────────────────────────────────── */
function StepRow({
  step,
  index,
  total,
}: {
  step: (typeof LOAN_STEPS)[0];
  index: number;
  total: number;
}) {
  const { t } = useTranslation();
  const Icon = step.icon;
  return (
    <div className="flex items-start gap-4 sm:gap-5">
      {/* Step indicator */}
      <div className="flex flex-col items-center">
        <div className="relative flex h-11 w-11 items-center justify-center rounded-full border-2 border-[#D4AF37]/40 bg-[#D4AF37]/10">
          <span className="absolute -top-2.5 -end-2 flex h-5 w-5 items-center justify-center rounded-full bg-[#D4AF37] text-[10px] font-bold text-background">
            {index + 1}
          </span>
          <Icon className="h-5 w-5 text-[#D4AF37]" />
        </div>
        {index < total - 1 && (
          <div className="h-10 w-px bg-gradient-to-b from-[#D4AF37]/40 to-transparent" />
        )}
      </div>
      {/* Content */}
      <div className="pt-1 pb-4">
        <h3 className="font-semibold text-foreground">
          {t(step.titleKey, step.fallbackTitle)}
        </h3>
        <p className="mt-1 text-sm leading-relaxed text-muted-foreground">
          {t(step.descKey, step.fallbackDesc)}
        </p>
      </div>
    </div>
  );
}

/* ────────────────────────────────────────────────────────────── */
/*  FAQ Block                                                    */
/* ────────────────────────────────────────────────────────────── */
function FaqBlock({ items }: { items: typeof LOAN_FAQ }) {
  const { t } = useTranslation();
  return (
    <div className="space-y-3">
      <h3 className="flex items-center gap-2 text-lg font-semibold text-foreground">
        <HelpCircle className="h-5 w-5 text-[#D4AF37]" />
        {t("lendGuide.faqTitle", "Frequently Asked Questions")}
      </h3>
      <Accordion type="single" collapsible className="w-full">
        {items.map((item, i) => (
          <AccordionItem key={i} value={`faq-${i}`} className="border-border/40">
            <AccordionTrigger className="text-sm font-medium text-foreground hover:text-[#D4AF37] hover:no-underline">
              {t(item.qKey, item.fallbackQ)}
            </AccordionTrigger>
            <AccordionContent className="text-sm leading-relaxed text-muted-foreground">
              {t(item.aKey, item.fallbackA)}
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  );
}

/* ────────────────────────────────────────────────────────────── */
/*  Safety Shield                                                */
/* ────────────────────────────────────────────────────────────── */
function SafetyShield() {
  const { t } = useTranslation();
  return (
    <Card className="border-[#D4AF37]/20 bg-card/40 backdrop-blur-sm overflow-hidden">
      <div className="relative">
        {/* Accent bar */}
        <div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-transparent via-[#D4AF37] to-transparent" />
        <div className="p-6 sm:p-8 space-y-6">
          <div className="flex items-center gap-3">
            <div className="flex h-11 w-11 items-center justify-center rounded-full border-2 border-[#D4AF37]/40 bg-[#D4AF37]/10">
              <ShieldCheck className="h-5 w-5 text-[#D4AF37]" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-foreground">
                {t("lendGuide.safetyTitle", "Security & Compliance")}
              </h2>
              <p className="text-xs text-muted-foreground">
                {t("lendGuide.safetySubtitle", "Your assets are protected by institutional-grade infrastructure")}
              </p>
            </div>
          </div>

          <div className="grid gap-4 sm:grid-cols-3">
            {SAFETY_ITEMS.map((item) => {
              const Icon = item.icon;
              return (
                <div
                  key={item.titleKey}
                  className="group rounded-xl border border-border/40 bg-background/40 p-5 transition-colors hover:border-[#D4AF37]/30"
                >
                  <div className="mb-3 flex h-10 w-10 items-center justify-center rounded-lg bg-[#D4AF37]/10">
                    <Icon className="h-5 w-5 text-[#D4AF37]" />
                  </div>
                  <h3 className="font-semibold text-foreground text-sm">
                    {t(item.titleKey, item.fallbackTitle)}
                  </h3>
                  <p className="mt-1.5 text-xs leading-relaxed text-muted-foreground">
                    {t(item.descKey, item.fallbackDesc)}
                  </p>
                </div>
              );
            })}
          </div>

          <div className="flex items-center justify-center gap-2 pt-2">
            <Badge variant="outline" className="border-[#D4AF37]/40 text-[#D4AF37] text-[10px]">
              MSB C100000015
            </Badge>
            <Badge variant="outline" className="border-border/40 text-muted-foreground text-[10px]">
              FINTRAC Regulated
            </Badge>
            <Badge variant="outline" className="border-border/40 text-muted-foreground text-[10px]">
              No Rehypothecation
            </Badge>
          </div>
        </div>
      </div>
    </Card>
  );
}

/* ────────────────────────────────────────────────────────────── */
/*  Exported Guide Sections                                      */
/* ────────────────────────────────────────────────────────────── */
export function LoanProductGuide() {
  const { t } = useTranslation();
  return (
    <section className="space-y-8">
      <Card className="border-border/40 bg-card/40 backdrop-blur-sm">
        <CardContent className="p-6 sm:p-8 space-y-6">
          <div className="space-y-1.5">
            <h2 className="text-xl font-bold text-foreground">
              {t("lendGuide.loanTitle", "How Crypto Loans Work")}
            </h2>
            <p className="text-sm text-muted-foreground">
              {t("lendGuide.loanSubtitle", "From collateral deposit to fund disbursement — a step-by-step guide.")}
            </p>
          </div>
          <div>
            {LOAN_STEPS.map((step, i) => (
              <StepRow key={step.titleKey} step={step} index={i} total={LOAN_STEPS.length} />
            ))}
          </div>
          <FaqBlock items={LOAN_FAQ} />
        </CardContent>
      </Card>
      <SafetyShield />
    </section>
  );
}

export function EarnProductGuide() {
  const { t } = useTranslation();
  return (
    <section className="space-y-8">
      <Card className="border-border/40 bg-card/40 backdrop-blur-sm">
        <CardContent className="p-6 sm:p-8 space-y-6">
          <div className="space-y-1.5">
            <h2 className="text-xl font-bold text-foreground">
              {t("lendGuide.earnTitle", "How Earn Interest Works")}
            </h2>
            <p className="text-sm text-muted-foreground">
              {t("lendGuide.earnSubtitle", "Deposit, earn daily, and withdraw anytime — completely flexible.")}
            </p>
          </div>
          <div>
            {EARN_STEPS.map((step, i) => (
              <StepRow key={step.titleKey} step={step} index={i} total={EARN_STEPS.length} />
            ))}
          </div>
          <FaqBlock items={EARN_FAQ} />
        </CardContent>
      </Card>
      <SafetyShield />
    </section>
  );
}
