/**
 * Build-time generator for pair sitemap files.
 *
 * Fetches every pair-batch sitemap from the dynamic-feed edge function,
 * splits them into 5,000-URL files (~9 MB each, well under the 50 MB /
 * 50,000-URL sitemap.org limit), and writes them as real static .xml files
 * to public/sitemap-pairs-N.xml so they resolve on the apex domain
 * (mrcglobalpay.com), since Lovable hosting doesn't honor _redirects proxy
 * rules for /sitemap-* paths.
 *
 * Also rewrites public/sitemap.xml as a same-host sitemapindex listing every
 * generated child, plus the small static + blog sitemaps.
 *
 * Runs automatically before every `vite build` via the `prebuild` script in
 * package.json — so every publish includes a sitemap that covers 100% of the
 * pairs currently in the database.
 */

import { writeFileSync, mkdirSync, readdirSync, unlinkSync } from "node:fs";
import { join } from "node:path";

const SUPABASE_URL = "https://tjikwxkmsfmyjkssvyoh.supabase.co";
const FEED_BASE = `${SUPABASE_URL}/functions/v1/dynamic-feed?p=`;
const URLS_PER_FILE = 5000;
const PUBLIC_DIR = "public";

type UrlEntry = string; // raw <url>...</url> XML chunk

const URL_RE = /<url>[\s\S]*?<\/url>/g;

async function fetchSourceBatch(idx: number): Promise<string | null> {
  const url = `${FEED_BASE}/sitemap-pairs-${idx}.xml`;
  const res = await fetch(url);
  if (!res.ok) return null;
  return await res.text();
}

function extractUrls(xml: string): UrlEntry[] {
  return xml.match(URL_RE) ?? [];
}

function wrapUrlset(entries: UrlEntry[]): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${entries.join("\n")}
</urlset>
`;
}

function wrapIndex(childPaths: string[]): string {
  const today = new Date().toISOString().slice(0, 10);
  const items = childPaths
    .map(
      (p) =>
        `  <sitemap><loc>https://mrcglobalpay.com/${p}</loc><lastmod>${today}</lastmod></sitemap>`,
    )
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Sitemap index for mrcglobalpay.com — auto-generated by scripts/build-sitemaps.ts.
  Children are real static files served from public/ so they resolve on apex.
  Regenerated on every build, so new pairs appear in the next deploy.
-->
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${items}
</sitemapindex>
`;
}

function clearOldPairFiles() {
  for (const f of readdirSync(PUBLIC_DIR)) {
    if (/^sitemap-pairs-\d+\.xml$/.test(f)) {
      unlinkSync(join(PUBLIC_DIR, f));
    }
  }
}

async function main() {
  console.log("[sitemaps] Fetching all pair URLs from dynamic-feed…");
  mkdirSync(PUBLIC_DIR, { recursive: true });

  // Fetch source batches sequentially until we get an empty/missing one.
  // The dynamic-feed function emits ~19,500 URLs per source batch (1,500
  // pairs × 13 langs); we re-split into 5,000-URL output files.
  const allUrls: UrlEntry[] = [];
  let sourceIdx = 0;
  let consecutiveEmpty = 0;
  while (consecutiveEmpty < 2 && sourceIdx < 100) {
    const xml = await fetchSourceBatch(sourceIdx);
    if (!xml) {
      consecutiveEmpty++;
      sourceIdx++;
      continue;
    }
    const entries = extractUrls(xml);
    if (entries.length === 0) {
      consecutiveEmpty++;
    } else {
      consecutiveEmpty = 0;
      allUrls.push(...entries);
      console.log(
        `[sitemaps]   source batch ${sourceIdx}: +${entries.length.toLocaleString()} URLs (total ${allUrls.length.toLocaleString()})`,
      );
    }
    sourceIdx++;
  }

  if (allUrls.length === 0) {
    console.warn("[sitemaps] No pair URLs returned — keeping existing files.");
    return;
  }

  console.log(`[sitemaps] Total pair URLs: ${allUrls.length.toLocaleString()}`);

  // Wipe stale pair files so removed batches don't linger in public/.
  clearOldPairFiles();

  // Split into output files of URLS_PER_FILE entries each.
  const childPaths: string[] = ["sitemap-static.xml", "sitemap-blog.xml"];
  const totalFiles = Math.ceil(allUrls.length / URLS_PER_FILE);
  for (let i = 0; i < totalFiles; i++) {
    const slice = allUrls.slice(i * URLS_PER_FILE, (i + 1) * URLS_PER_FILE);
    const filename = `sitemap-pairs-${i}.xml`;
    writeFileSync(join(PUBLIC_DIR, filename), wrapUrlset(slice), "utf8");
    childPaths.push(filename);
  }
  console.log(
    `[sitemaps] Wrote ${totalFiles} pair sitemap files (${URLS_PER_FILE.toLocaleString()} URLs each).`,
  );

  // Refresh the small static + blog sitemaps from the dynamic feed too,
  // so they always reflect the latest blog posts and landing pages.
  for (const name of ["sitemap-static.xml", "sitemap-blog.xml"]) {
    const res = await fetch(`${FEED_BASE}/${name}`);
    if (res.ok) {
      const body = await res.text();
      writeFileSync(join(PUBLIC_DIR, name), body, "utf8");
      console.log(`[sitemaps] Refreshed ${name} (${body.length.toLocaleString()} bytes).`);
    } else {
      console.warn(`[sitemaps] Could not refresh ${name} (HTTP ${res.status}) — leaving existing copy.`);
    }
  }

  // Write the same-host sitemap index.
  writeFileSync(join(PUBLIC_DIR, "sitemap.xml"), wrapIndex(childPaths), "utf8");
  console.log(
    `[sitemaps] Wrote sitemap.xml index with ${childPaths.length} children.`,
  );
}

main().catch((err) => {
  console.error("[sitemaps] Generator failed:", err);
  // Don't fail the build — keep whatever sitemap files already exist.
  process.exit(0);
});
